# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2024 Jason Yundt <jason@jasonyundt.email>
%YAML 1.2
---
repos:
    -
        repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
        rev: v0.5.1post1
        hooks:
            - id: pre-commit-update
    -
        repo: https://github.com/Jayman2000/jasons-pre-commit-hooks
        rev: v0.2.0
        hooks:
            -
                id: repo-style-checker
                args:
                    # All of repo-style-checker’s README-related checks
                    # only make sense if you’re creating a README for a
                    # regular repository. They don’t make sense for
                    # GitHub profile READMEs.
                    - --skip
                    - README.md exists
                    - --skip
                    - README.md has <h1>
                    - --skip
                    - names match
                    - --skip
                    - README.md links to copying.md
                    - --skip
                    - README.md has hints
                    - --skip
                    - standard hints
            -
                id: detect-bad-unicode
                exclude: &default_exclude ^LICENSES/
            -
                id: forbid-paths-that-match
                exclude: *default_exclude
                args:
                    - --pattern
                    - ^LICENSE
                    - --pattern
                    - ^COPYING
    -
        repo: https://github.com/fsfe/reuse-tool
        rev: v4.0.3
        hooks:
            - id: reuse
    -
        repo: https://github.com/editorconfig-checker/editorconfig-checker.python
        rev: 3.0.3
        hooks:
            -
                id: editorconfig-checker
                exclude: *default_exclude
                args:
                    - -ignore-defaults
    -
        repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.6.0
        hooks:
            -
                id: check-case-conflict
                exclude: *default_exclude
            -
                id: check-merge-conflict
                exclude: *default_exclude
            -
                id: check-symlinks
                exclude: *default_exclude
            -
                id: check-vcs-permalinks
                exclude: *default_exclude
            -
                id: destroyed-symlinks
                exclude: *default_exclude
    -
        repo: https://github.com/pre-commit/pygrep-hooks
        rev: v1.10.0
        hooks:
            -
                id: text-unicode-replacement-char
                exclude: *default_exclude
    -
        repo: https://github.com/zricethezav/gitleaks
        rev: v8.19.3
        hooks:
            -
                id: gitleaks
                exclude: *default_exclude
    -
        repo: https://github.com/Jayman2000/yamllint-pr
        rev: pr630-rev-9
        hooks:
            -
                id: yamllint
                exclude: *default_exclude
