# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2024 Jason Yundt <jason@jasonyundt.email>
%YAML 1.2
---
repos:
    -
        repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
        rev: v0.5.1post1
        hooks:
            - id: pre-commit-update
    -
        repo: https://github.com/Jayman2000/jasons-pre-commit-hooks
        rev: v0.2.0
        hooks:
            -
                id: repo-style-checker
                args:
                    # All of repo-style-checker’s README-related checks
                    # only make sense if you’re creating a README for a
                    # regular repository. They don’t make sense for
                    # GitHub profile READMEs.
                    - --skip
                    - README.md exists
                    - --skip
                    - README.md has <h1>
                    - --skip
                    - names match
                    - --skip
                    - README.md links to copying.md
                    - --skip
                    - README.md has hints
                    - --skip
                    - standard hints
    -
        repo: https://github.com/fsfe/reuse-tool
        rev: v4.0.3
        hooks:
            - id: reuse
